### ISSUE TITLE
🖥️ website: tailwindcss installation & setup

### ISSUE THREAD

**Issue by nicokempe** [NicoKempeEU/discord-bot#16]
**Planned Changes:**
* [ ] Install the latest Tailwind CSS version
* [ ] Setup the tailwind.config.js file
* [ ] Add the Tailwind directives to CSS
* [ ] Import the CSS file
* [ ] Test the usage

**Comment by felixunrein** [comment]
#33 

**Planned Changes:**

- [x] Install the latest Tailwind CSS version
- [x] Setup the tailwind.config.js file
- [x] Add the Tailwind directives to CSS
- [x] Import the CSS file
- [x] Test the usage
