### ISSUE TITLE
🖥️ Website: Authentication System

### ISSUE THREAD

**Issue by felixunrein** [NicoKempeEU/discord-bot#37]
### What problem does this feature solve?

- [ ] #18 
- [ ] #39 (Authentication views)
- [ ] Axios installation
- [ ] Vuex  installation
- [ ] Vuex store configuration
- [ ] Login storage in vuex
- [ ] Implement login functionality in router

If I forget anything feel free to write a comment.

**Comment by nicokempe** [comment]
1. What do you mean by 'Add forms'?
2. The connection between the projects already have a issue opened (#18 / #19)

**Comment by nicokempe** [comment]
Like you can see in the [server-setup feature branch](https://github.com/NicoKempeEU/discord-bot/tree/feature/server-setup) we switched to Spring Boot for the software backend. That makes this issue irrelevant / outdated.
